apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sample-app
  labels:
    name: my-sample-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-sample-app
  template:
    metadata:
      labels:
        app: my-sample-app
    spec:
      containers:
        - name: my-sample-app
          image: ghcr.io/jasonsmithio/my-sample-app:v1
          imagePullPolicy: Always
          ports:
            - name: frontend
              containerPort: 8888
              protocol: TCP