apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: secondtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-sample-app
  labels:
    name: second-sample-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-sample-app
  template:
    metadata:
      labels:
        app: second-sample-app
    spec:
      containers:
        - name: second-sample-app
          image: ghcr.io/jasonsmithio/my-sample-app:v2
          imagePullPolicy: Always
          ports:
            - name: backend-port
              containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
    name: backend
spec:
    selector:
        app: second-sample-app
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000